apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-code-server
  namespace: default
  labels:
    app: status-code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-code-server
  template:
    metadata:
      labels:
        app: status-code-server
    spec:
      containers:
      - name: status-code-server
        image: docker.io/pszeto/status-code-server
        imagePullPolicy: Always
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
        - name: STATUS_CODE
          value: "503"         
        ports:
        - containerPort: 8080
        - containerPort: 8443
