kind: Service
apiVersion: v1
metadata:
  name: status-code-server
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: status-code
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443